[package]
name = "nbnet"
version = "0.1.0"
edition = "2021"
authors = ["fhfanhui@gmail.com"]
build = "build.rs"

[dependencies]
clap = { version = "4.5", features = [ "derive" ] }

serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

rayon = "1.10.0"
# parking_lot = "0.12"

# self-maintained crates
ruc = { version = "7.2", features = [ "http", "algo_rand" ] }

# chaindev = "0.32.0"
chaindev = { git = "https://github.com/rust-util-collections/chaindev", branch = "master" }

[build-dependencies]
vergen = "9.0"

[dev-dependencies]

[features]
default = []

[patch.crates-io]
# ruc = { path = "../ruc" }
# vsdb = { path = "../vsdb/wrappers" }

[patch."https://github.com/rust-util-collections/chaindev"]
chaindev = { path = "../chaindev" }

[profile.release]
lto = "thin"
overflow-checks = true
